version: '3'

services:
 
  api:
    container_name: api
    image: api-ia-aws:latest
    volumes:
      - ./images:/app/images
      - ./logs:/app/logs
      - ./assets:/app/assets
      - ./src:/app/src
    environment:
      PORT: 8000
      VIRTUAL_HOST: 0.0.0.0, 127.0.0.1,
      VIRTUAL_PORT: 8000
      LETSENCRYPT_HOST: algo.ralejandro.com
      LETSENCRYPT_EMAIL: ralejandrobm@gmail.com
    ports:
      - '8000:8000'
    restart: "always"
    networks:
      - web
    command: [ "python", "app.py", "--app", "ApiApp" ]


networks:
  web:
    external: true
